plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id 'org.jetbrains.kotlin.plugin.compose'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')

if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { inputStream ->
        localProperties.load(inputStream)
    }
}

android {
    namespace 'yos.music.player'
    compileSdk 34

    signingConfigs {
        debug {
            storeFile rootProject.file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            def releaseStoreFile = localProperties.getProperty("flamingo.release.storeFile")

            if (releaseStoreFile != null) {
                storeFile rootProject.file(releaseStoreFile)
                storePassword localProperties.getProperty("flamingo.release.storePassword")
                keyAlias localProperties.getProperty("flamingo.release.keyAlias")
                keyPassword localProperties.getProperty("flamingo.release.keyPassword")
            }
        }
    }

    defaultConfig {
        applicationId "yos.music.player"
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName "2.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

        renderscriptTargetApi 19
        renderscriptSupportModeEnabled true
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            applicationVariants.all { variant ->
                if (variant.buildType.name == 'release') {
                    variant.outputs.all {
                        def appName = "Flamingo"
                        def versionName = variant.versionName
                        def date = new Date().format('yyMMddHHmm')
                        outputFileName = "${appName}_${versionName}_${date}.ApK"
                    }
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    composeOptions {
        kotlinCompilerExtensionVersion '2.0.0'
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        compose true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    composeCompiler {
        enableStrongSkippingMode = true
        stabilityConfigurationFile = file "${project.rootDir}/stability_config.conf"
    }

}

dependencies {
    implementation files(
        "libs/kenburnsview-1.0.7.aar",
        "libs/libPhonograph-release.aar",
        "libs/lib-decoder-ffmpeg-release.aar"
    )
    implementation project(":overscroll_core")

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.4'
    implementation 'androidx.activity:activity-compose:1.9.1'

    implementation 'androidx.compose.ui:ui:1.7.1'
    implementation 'androidx.compose.ui:ui-graphics:1.7.1'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.7.1'
    implementation 'androidx.compose.animation:animation:1.7.1'
    implementation 'androidx.compose.foundation:foundation:1.7.1'
    implementation 'androidx.compose.foundation:foundation-layout:1.7.1'
    implementation 'sh.calvin.reorderable:reorderable:2.5.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.compose.runtime:runtime-livedata:1.7.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.7.1'
    debugImplementation 'androidx.compose.ui:ui-tooling:1.7.1'
    debugImplementation 'androidx.compose.ui:ui-test-manifest:1.7.1'

    implementation 'androidx.compose.material3:material3:1.2.1'
    implementation 'androidx.compose.material:material-icons-core:1.7.1'
    implementation 'androidx.compose.material:material-icons-extended:1.7.1'

    implementation "io.coil-kt:coil-compose:2.5.0"

    implementation 'com.google.accompanist:accompanist-insets:0.16.1'
    implementation 'com.google.accompanist:accompanist-insets-ui:0.16.1'
    implementation 'com.google.accompanist:accompanist-navigation-animation:0.31.4-beta'
    implementation "com.google.accompanist:accompanist-systemuicontroller:0.23.1"

    implementation('com.blankj:utilcodex:1.31.1') {
        exclude group: 'androidx.appcompat'
    }

    def media3_version = "1.4.0"
    implementation "androidx.media3:media3-session:$media3_version"
    implementation "androidx.media3:media3-exoplayer:$media3_version"
    implementation "androidx.media3:media3-exoplayer-dash:$media3_version"

    implementation 'com.tencent:mmkv-static:2.4.0'

    implementation 'com.google.code.gson:gson:2.10.1'

    implementation 'com.github.xiaowine:Lyric-Getter-Api:6.0.0'

    implementation "com.github.Kyant0:taglib:1.0.0-alpha25"

    implementation 'androidx.graphics:graphics-path:1.1.0'

    implementation "com.google.accompanist:accompanist-pager:0.20.2"

    implementation 'androidx.appcompat:appcompat:1.7.0'

    implementation('io.github.alexzhirkevich:cupertino:0.1.0-alpha04')
    implementation('io.github.alexzhirkevich:cupertino-icons-extended:0.1.0-alpha04')

    implementation "androidx.core:core-splashscreen:1.0.1"

    implementation("com.github.FunnySaltyFish.ComposeDataSaver:data-saver:1.1.9") {
        exclude group: 'androidx.compose'
    }

    implementation "com.github.promeg:tinypinyin:2.0.2"

    implementation("dev.chrisbanes.haze:haze:0.9.0-alpha06") {
        exclude group: "androidx.compose.ui", module: "ui"
        exclude group: "androidx.compose.ui", module: "ui-graphics"
        exclude group: "androidx.compose.animation", module: "animation"
        exclude group: "androidx.compose.material3", module: "material3"
    }
    implementation("dev.chrisbanes.haze:haze-materials:0.9.0-alpha06") {
        exclude group: "androidx.compose.ui", module: "ui"
        exclude group: "androidx.compose.ui", module: "ui-graphics"
        exclude group: "androidx.compose.animation", module: "animation"
        exclude group: "androidx.compose.material3", module: "material3"
    }
}

configurations.all {
    exclude group: 'org.jetbrains.compose.runtime'
    exclude group: 'org.jetbrains.compose.ui'
    exclude group: 'org.jetbrains.compose.foundation'
    exclude group: 'org.jetbrains.compose.animation'
    exclude group: 'org.jetbrains.compose.material'
    exclude group: 'org.jetbrains.compose.material3'

    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def group = details.requested.group
        if (group == 'androidx.compose.ui' ||
            group == 'androidx.compose.animation' ||
            group == 'androidx.compose.foundation' ||
            group == 'androidx.compose.runtime' ||
            group == 'androidx.compose.material') {
            details.useVersion '1.7.1'
        }
        if (group == 'androidx.compose.material3') {
            details.useVersion '1.2.1'
        }
    }
}
